CREATE TABLE animal (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255) NOT NULL,
   age INT NOT NULL,
   race VARCHAR(255) NOT NULL,
   enter_date date NOT NULL,
   exit_date date,
   arrival_conditions VARCHAR(255) NOT NULL,
   received_name VARCHAR(255) NOT NULL,
   date_of_death date,
   size VARCHAR(255) NOT NULL,
   CONSTRAINT pk_animal PRIMARY KEY (id)
);